### ISSUE TITLE
ActionView::Template::Error (Missing partial banner/_project_body_bottom

### ISSUE THREAD

**Issue by asakura0603** [akiko-pusu/redmine_banner#94]
Hi akiko-pusu, I`m asakura0603.
Today, I have an error about "Redmine 500 Internal Error", when I introducing redmine_banner.
please give me advice.

OS : Windows 7
Redmine : Bitnami Redmine 3.4.4-3

```production.log
Started GET "/redmine/projects/boma" for 127.0.0.1 at 2018-05-22 17:30:23 +0900
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"boma"}
  Current user: anonymous
Redirected to http://127.0.0.1:3001/redmine/login?back_url=http%3A%2F%2F127.0.0.1%3A3001%2Fredmine%2Fprojects%2Fboma
Filter chain halted as :authorize rendered or redirected
Completed 302 Found in 3561ms (ActiveRecord: 1397.0ms)
Started GET "/redmine/login?back_url=http%3A%2F%2F127.0.0.1%3A3001%2Fredmine%2Fprojects%2Fboma" for 127.0.0.1 at 2018-05-22 17:30:29 +0900
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://127.0.0.1:3001/redmine/projects/boma"}
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (175.0ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (10.0ms)
Completed 500 Internal Server Error in 3028ms (ActiveRecord: 424.0ms)

ActionView::Template::Error (Missing partial banner/_project_body_bottom with {:locale=>[:ja, :en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :rsb]}. Searched in:
  * "C:/Bitnami/redmine-3.4.4-3/apps/redmine/htdocs/plugins/redmine_work_time/app/views"
  * "C:/Bitnami/redmine-3.4.4-3/apps/redmine/htdocs/plugins/easy_gantt/app/views"
  * "C:/Bitnami/redmine-3.4.4-3/apps/redmine/htdocs/app/views"
  * "C:/Bitnami/redmine-3.4.4-3/ruby/lib/ruby/gems/2.3.0/gems/redmine_extensions-0.2.9/app/views"
):
    88: 							<%= yield :sidebar %>
    89: 							<%= view_layouts_base_sidebar_hook_response %>
    90: 						</div>
    91: 						<div id="content">
    92: 							<%= render_flash_messages %>
    93: 							<%= yield %>
    94: 							<!-- <%= call_hook :view_layouts_base_content %> -->
  plugins/redmine_banner-master/lib/banner_application_hooks.rb:17:in `view_layouts_base_content'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:91:in `_app_views_layouts_base_html_erb__203227295_41807196'
  app/controllers/application_controller.rb:491:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:489:in `render_error'
  app/controllers/application_controller.rb:477:in `render_404'
  app/controllers/application_controller.rb:501:in `missing_template'

```

**Comment by akiko-pusu** [comment]
@asakura0603 
Sorry I could not reply for this issue.
It seems you store redmine banner plugin as "redmine_banner-master" under plugins directory.

Plugin name should be stored the same name described at init.rb.
For example, Redmine Banner plugin should be stored as "redmine_banner".

```
Redmine::Plugin.register :redmine_banner do
  name 'Redmine Banner plugin'
  author 'Akiko Takano'
  author_url 'http://twitter.com/akiko_pusu'
  description 'Plugin to show site-wide message, such as maintenacne informations or notifications.'
  version '0.1.2'
  requires_redmine version_or_higher: '2.5.0'
  url 'https://github.com/akiko-pusu/redmine_banner'
  
  # snip
end

```
